(-> (make-elevator-sim (->ElevatorCfg s/closest-stopped-or-closest-moving-strategy 5 4))
    (pickup 1 4)
    (tick-view)
    (tick-view)
    (pickup 4 0)
    (tick-view)
    (pickup 0 1)
    (tick-view)
    (pickup 2 4)
    (tick-view)
    (pickup 4 3)
    (pickup 2 4)
    (tick-view-until-finished)
    )
